sudo: required

language: go

services:
  - docker

go:
  - 1.7

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - cotdsa

script:
  - make bootstrap
  - ln -s . vendor/github.com/hashicorp/vault
  - XC_OS="linux" XC_OSARCH="linux/386 linux/amd64" make bin
  - make test
